// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlHrW44xdfEAU4ZzGurVqAmWq492WOoXk',
    appId: '1:252316973650:web:f291b262399c4b8704bd8b',
    messagingSenderId: '252316973650',
    projectId: 'grocerease-56442',
    authDomain: 'grocerease-56442.firebaseapp.com',
    storageBucket: 'grocerease-56442.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYzZBi2UTXGQobRgPFTETInIWCSlFbVtI',
    appId: '1:252316973650:android:48b336002a13dc4d04bd8b',
    messagingSenderId: '252316973650',
    projectId: 'grocerease-56442',
    storageBucket: 'grocerease-56442.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-QaVAC7E96zQMvXzk_TQY5USt4bN6pDc',
    appId: '1:252316973650:ios:37a417d771a3cc8f04bd8b',
    messagingSenderId: '252316973650',
    projectId: 'grocerease-56442',
    storageBucket: 'grocerease-56442.appspot.com',
    iosBundleId: 'com.example.proyectosflutter',
  );

}